from pathlib import Path

PLUGIN_VERSION = "1.6.1"
STRUCTURED_SCHEMA_VERSION = "v7"
WIKI_API_URL = "https://terraria.wiki.gg/zh/api.php"
WIKI_BASE_URL = "https://terraria.wiki.gg/zh/wiki/"
REQUEST_TIMEOUT_SECONDS = 10
SUMMARY_LENGTH_LIMIT = 300
CARD_SUMMARY_LENGTH_LIMIT = 220
SEARCH_CANDIDATE_LIMIT = 8
ALTERNATIVE_CANDIDATE_LIMIT = 3
QUERY_CACHE_TTL_SECONDS = 600
NEGATIVE_CACHE_TTL_SECONDS = 90
PAGE_CACHE_TTL_SECONDS = 600
SEARCH_CACHE_TTL_SECONDS = 300
GUIDE_CACHE_TTL_SECONDS = 900
REDIRECT_CACHE_TTL_SECONDS = 900
PERSISTENT_CACHE_TTL_SECONDS = 86400
CACHE_MAX_ENTRIES = 256
THUMBNAIL_WIDTH = 320
CARD_FOOTER = "Terraria Wiki"
GUIDE_PAGE_LENGTH_THRESHOLD = 50000
GUIDE_SECTION_THRESHOLD = 8
GUIDE_MAX_SECTIONS = 4
GUIDE_SECTION_SUMMARY_LIMIT = 120
GUIDE_NAMESPACE_NAME = "Guide"
STRUCTURED_SUMMARY_LIMIT = 4
STRUCTURED_RECIPE_LIMIT = 2
CARGO_QUERY_LIMIT = 20
ICON_PREFETCH_INTERVAL_SECONDS = 6 * 60 * 60
ICON_PREFETCH_MAX_ICONS = 8
ICON_PREFETCH_FILES = (
    "Iron Anvil.png",
    "Lead Anvil.png",
    "Mythril Anvil.png",
    "Orichalcum Anvil.png",
    "Copper Bar.png",
    "Terra Blade.png",
    "Zenith.png",
    "Life Crystal.png",
)
PERSISTENT_CACHE_PATH = str(Path(__file__).resolve().parent.parent / ".terraria_wiki_cache.sqlite3")
